### ISSUE TITLE
How to install locally

### ISSUE THREAD

**Issue by evanluzi** [rbarton65/espnff#1]
Hey there,

Sorry for creating an issue, but I came across this script and would love to use it for my league. Problem is, I'm a noob with Python and I'm not sure how to get the rankings returned. Are there any beginner tutorials you could point me towards (or simple instructions) on how to run this locally on OS X to get the rankings? I've got MAMP and Coda installed if that helps. Thank you!

**Comment by rbarton65** [comment]
Hey Evan,

Assuming you don't have Python 3.x installed, for OSX I would do the following in Terminal:

1. Install [Homebrew](http://brew.sh/). This allows you to install `git` and `python3` through Terminal, which are necessities for using this package.

2. Install `git`

    `brew install git`

3. Install `python3`

   `brew install python3`

4. Install the package with `git`

    `git clone https://github.com/rbarton65/espnff`

5. Switch to the `espnff` directory

    `cd espnff`

6. Run `setup.py`

    `python3 setup.py install`

7. Open Python 3 in Terminal

    `python3`

8. Follow the Usage section in `README.md`

    ```
    from espnff import League

    league_id = '''insert league id'''
    year = '''insert league year'''

    league = League(league_id, year)

    print(league.get_week(week))
    ```

This should return a dictionary of power rankings for the week you defined in `league.get_week(week)`. 

Hope this helps.

**Comment by evanluzi** [comment]
Thank you so much! I'm almost there, but I'm getting a ValueError from terminal when I'm doing the script. Here's the results:

```python
>>> from espnff import League
>>> league_id = "671589"
>>> year = "2016"
>>> league = League(league_id, year)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/evan/Desktop/espnff/espnff/power_rankings.py", line 23, in __init__
    self._fetch_members()
  File "/Users/evan/Desktop/espnff/espnff/power_rankings.py", line 36, in _fetch_members
    self.members.append(Members(team_name, team_id, self.league_id, self.year))
  File "/Users/evan/Desktop/espnff/espnff/power_rankings.py", line 151, in __init__
    self._fetch_info()
  File "/Users/evan/Desktop/espnff/espnff/power_rankings.py", line 171, in _fetch_info
    team_score = float(score.text[2:].split('-')[0])  # 'W 98-85' will return '98', need float for decimals
ValueError: could not convert string to float: 'x'
>>> print(league.get_week(1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'league' is not defined
```

Any thoughts?

**Comment by rbarton65** [comment]
Should be fixed now. Looks like for games unplayed, the url it's scraping shows "Box" as a score instead of "0". It took the last letter "x" and tried to convert it to an float. Try again from step 4! Re-download the repository and go from there.

**Comment by evanluzi** [comment]
Awesome, that worked perfectly. Thank you so much! My league is going to love this. I was able to create this sweet graphic using your rankings: 
![luzi-earley_ff_powerranks_week1](https://cloud.githubusercontent.com/assets/5759355/18566247/2651e7b8-7b61-11e6-80c8-0bd0c02ff382.jpg)

**Comment by rbarton65** [comment]
Well damn, that looks amazing. Glad it's working for you! If you find any more issues, you know where to find me!

**Comment by evanluzi** [comment]
Will do and thanks again! If you want a PSD of the graphic for your own use, let me know and I'll get it to you as a (small) repayment for your help.

One thing I will mention – should anybody else stumble across this – is that I had to install the Xcode command line tools before the step-by-step you provided would work fully.
