### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by CMorton737** [rbarton65/espnff#19]
It appears that ESPN has disallowed access to this data unfortunately

**Comment by rbarton65** [comment]
ESPN is performing routine maintenance on their servers for the upcoming season - the information should be available once they are done! Notice how you can't log into the website either.

**Comment by CMorton737** [comment]
Ah, duh! I supposed I should have tried to log in before posting :)

**Comment by rbarton65** [comment]
Closing this issue now that maintenance is over.
