### ISSUE TITLE
What is the .mov in the example?

### ISSUE THREAD

**Issue by bluesforsalvador** [rbarton65/espnff#30]
Hello,

Hopfully this is something simple, but what is the .mov in the example?

>>> team1.mov
[32.12, 24.92, 45.97, 34.17, 41.74, -5.39, 1.15, 0, 0, 0, 0, 0, 0, 0]

Thanks!

P.S. I'm doing a unique scoring system so this is really helping my automate the scoring each week and display it on a web page, thanks so much!!

**Comment by rbarton65** [comment]
Hello,

Thanks for taking a look at my wrapper! `.mov` is margin of victory, i.e. if team 1 scores 100 points compared to the opponent's 80 points, team 1's margin of victory is 20.
